name: CI

on: 
  push:
  schedule:
    - cron: '0 19 * * 5'

jobs:
  Merge-Upstream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fork Sync With Upstream
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
      with:
        upstream_repository: NationalSecurityAgency/ghidra
        upstream_branch: master
        target_branch: master
        git_pull_args: --rebase=merges
        git_push_args: --force

  Build:
    needs: [Merge-Upstream]
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
          java-version: 11.0.4
          architecture: x64

    - name: Build Dependencies (Windows)
      if: matrix.platform == 'windows-latest'
      run: |
        choco install winflexbison
        ren "C:\ProgramData\chocolatey\bin\win_bison.exe" "bison.exe"
        ren "C:\ProgramData\chocolatey\bin\win_flex.exe" "flex.exe"
          
    - name: Build Dependencies (Linux)
      if: matrix.platform == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y bison flex
        
    - name: Build Dependencies (macOS)
      if: matrix.platform == 'macos-latest'
      run: brew install bison flex curl

    - name: Build with Gradle
      continue-on-error: true
      run: gradle --init-script gradle/support/fetchDependencies.gradle init && gradle buildGhidra
          
    - name: Upload a Build Artifacts  
      if: ${{ always() }}
      uses: actions/upload-artifact@v2.2.0
      with:
        name: ghidra-${{ matrix.platform }}-dev
        path: build/dist/ghidra_*.zip